name: Continuous Delivery

on:
  workflow_dispatch:

jobs:
  Build:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Set up Node.js
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          node-version: 17
          registry-url: 'https://registry.npmjs.org'

      - name: Install Node.js dependencies
        run: npm i

      - name: Link Project
        run: npm link

      - name: Test Sern
        run: sern

  Publish:
    name: Publishing to npm
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Publish to npm
        run: npm publish . --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

